# Generated by Django 3.1.4 on 2020-12-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201209_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='comment',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_comment',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_visited',
            field=models.BooleanField(default=False),
        ),
    ]
