# Generated by Django 3.1.4 on 2020-12-10 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20201209_1355"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="working_hours",
        ),
        migrations.AddField(
            model_name="doctor",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="WorkingSchedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("is_available", models.BooleanField(default=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.doctor"
                    ),
                ),
            ],
        ),
    ]
