# Generated by Django 3.1.4 on 2020-12-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201210_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='comment',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_comment',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
