# Generated by Django 3.1.4 on 2020-12-12 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201210_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingschedule',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='WorkingSchedule',
        ),
    ]
